{
 "title": "Simple HTTP BlackBox Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "url",
    "label": "URL",
    "query": "label_values(sample_external_url_up, url)"
   }
  ]
 },
 "panels": [
  {
   "title": "URL Response Time",
   "type": "graph",
   "description": "Shows the response time of the URLs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=~\"$url\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "URLs Up",
   "type": "singlestat",
   "description": "The number of active URLs",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sample_external_url_up == 1)"
    }
   ]
  },
  {
   "title": "Uptime (1 month)",
   "type": "gauge",
   "description": "The uptime of the URLs for the duration of 1 month",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (sample_external_url_up{url=~\".*\"})\n      or\n    (0 * sum_over_time(sample_external_url_up{url=~\".*\"}[30d]))\n  )[30d:5m]\n) * 100",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "All URLs",
   "type": "singlestat",
   "description": "All tested URLs",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(sample_external_url_up)" }
   ]
  }
 ]
}